CREATE TABLE IF NOT EXISTS `tweets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TEXT NOT NULL,
  `source` VARCHAR() NOT NULL,
  'original_text' VARCHAR() NOT NULL,
  `clean_text` TEXT DEFAULT NULL,
  `sentiment` INT DEFAULT NULL,
  `polarity` FLOAT DEFAULT NULL,
  `subjectivity` FLOAT DEFAULT NULL,
  `lang` TEXT DEFAULT NULL,
  'statuses_count' INT DEFAULT NULL,
  `favorite_count` INT DEFAULT NULL,
  `retweet_count` INT DEFAULT NULL,
  `original_author` TEXT DEFAULT NULL,
  `followers_count` INT DEFAULT NULL,
  `friends_count` INT DEFAULT NULL,
  'possibly_sensitive' VARCHAR() NOT NULL,
  `hashtags` TEXT DEFAULT NULL,
  `user_mentions` TEXT DEFAULT NULL,
  `place` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE utf8mb4_unicode_ci;